### ISSUE TITLE
moduleNotfounderror

### ISSUE THREAD

**Issue by ghost** [cuducos/scrapy-memcached-cache#2]
Bom dia Eduardo! eu rodei o comando python -i scrapy_memcached_cache.py, as esta dando este erroModuleNotFoundError.
Eu estou usando python 3.6, será que tem alguma incompatibilidade com esse module memcache?

b1@Matrix:~/Área de Trabalho$ python -i scrapy_memcached_cache.py
Traceback (most recent call last):
  File "scrapy_memcached_cache.py", line 9, in <module>
    from memcache import Client
ModuleNotFoundError: No module named 'memcache'

**Comment by cuducos** [comment]
I see you've already closed the issue, but just as reminder if anyone else ends up in the same situation:

There is a reason why we use package managers. Following the instructions (`pip install …` or `pipenv install …`)  is way better than`python -i scrapy_memcached_cache.py` because it manages not only packages, but its dependencies 👍 

In this specific case it will assure you have installed [the dependencies](https://github.com/cuducos/scrapy-memcached-cache/blob/906bd4fe191269d0d46d2316f23b029037830cc1/setup.py#L19) and avoid `ModuleNotFoundError: No module named 'memcache'` ; )
